language: go

go:
- 1.12.x

git:
  depth: 1

before_install:
- go get github.com/mattn/goveralls
- openssl aes-256-cbc -K $encrypted_8bed37950213_key -iv $encrypted_8bed37950213_iv
  -in client-secret.json.enc -out client-secret.json -d

before_deploy:
- curl 'https://goreportcard.com/checks' -H 'Accept: application/json, text/javascript, */*; q=0.01' --compressed -H 'Content-Type: application/x-www-form-urlencoded; charset=UTF-8' -H 'X-Requested-With: XMLHttpRequest' -H 'DNT: 1' -H 'Connection: keep-alive' -H 'Referer: https://goreportcard.com/report/github.com/rfinochi/golang-workshop-todo' --data 'repo=github.com%2Frfinochi%2Fgolang-workshop-todo'
- rm  ./docs/docs.go
- rm  ./docs/swagger.json
- rm  ./docs/swagger.yaml
- rm  ./LICENSE
- rm  ./README.md
- rm  ./.travis.yml
- go get -u github.com/swaggo/swag/cmd/swag
- swag init

before_script:
  - sleep 15
  - mongo mydb_test --eval 'db.createUser({user:"travis",pwd:"test",roles:["readWrite"]});'

script:
  - $GOPATH/bin/goveralls -service=travis-ci

services:
  - mongodb

deploy:
  skip_cleanup: true
  provider: gae
  keyfile: client-secret.json
  project: golang-workshop-todo
