language: go

go:
- 1.13.x

git:
  depth: 1

before_install:
- go get github.com/mattn/goveralls
- openssl aes-256-cbc -K $encrypted_8bed37950213_key -iv $encrypted_8bed37950213_iv
  -in client-secret.json.enc -out client-secret.json -d

before_deploy:
- curl 'https://goreportcard.com/checks' -d 'repo=github.com%2Frfinochi%2Fgolang-workshop-todo'
- rm ./docs/docs.go
- rm ./docs/swagger.json
- rm ./docs/swagger.yaml
- rm ./LICENSE
- rm ./README.md
- rm ./.travis.yml
- cp ./cmd/web/main_test.go ./main_test.go
- cp ./cmd/web/main.go ./main.go
- rm ./cmd/web/main_test.go
- rm ./cmd/web/main.go
- rmdir ./cmd/web
- rmdir ./cmd
- go get -u github.com/swaggo/swag/cmd/swag
- swag init

before_script:
  - sleep 15
  - mongo mydb_test --eval 'db.createUser({user:"travis",pwd:"test",roles:["readWrite"]});'

script:
  - $GOPATH/bin/goveralls -service=travis-ci

services:
  - mongodb

deploy:
  skip_cleanup: true
  provider: gae
  keyfile: client-secret.json
  project: golang-workshop-todo
