dist: focal
arch: amd64

language: go

go:
- 1.16.x

git:
  depth: 1

before_install:
- go get github.com/mattn/goveralls
- openssl aes-256-cbc -K $encrypted_8bed37950213_key -iv $encrypted_8bed37950213_iv
  -in client-secret.json.enc -out client-secret.json -d

before_deploy:
# curl 'https://goreportcard.com/checks' -d 'repo=github.com%2Frfinochi%2Fgolang-workshop-todo'
- rm ./docs/docs.go
- rm ./docs/swagger.json
- rm ./docs/swagger.yaml
- rm ./LICENSE
- rm ./README.md
- rm ./.travis.yml
- cp ./cmd/web/application.go ./application.go
- cp ./cmd/web/handlers.go ./handlers.go
- cp ./cmd/web/main.go ./main.go
- cp ./cmd/web/middleware.go ./middleware.go
- cp ./cmd/web/REVISION ./REVISION
- cp ./cmd/web/routes.go ./routes.go
- rm ./cmd/web/application.go
- rm ./cmd/web/handlers_test.go
- rm ./cmd/web/handlers.go
- rm ./cmd/web/main_test.go
- rm ./cmd/web/main.go
- rm ./cmd/web/middleware.go
- rm ./cmd/web/REVISION
- rm ./cmd/web/routes.go
- rmdir ./cmd/web
- rmdir ./cmd
- echo $TRAVIS_BUILD_NUMBER > REVISION
- go get -u github.com/swaggo/swag/cmd/swag
- swag init

before_script:
  - sleep 15
  - mongo mydb_test --eval 'db.createUser({user:"travis",pwd:"test",roles:["readWrite"]});'

script:
  - $GOPATH/bin/goveralls -service=travis-ci

services:
  - mongodb

deploy:
  skip_cleanup: true
  provider: gae
  keyfile: client-secret.json
  project: golang-workshop-todo
